module.exports = {
  breakpoints: ["600px", "900px", "1200px", "1800px"],
  space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
  fonts: {
    body:
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    heading: "inherit",
    monospace: "Menlo, monospace",
  },
  fontSizes: [
    ".5rem",
    "1rem",
    "1.5rem",
    "2rem",
    "3rem",
    "4rem",
    "5rem",
    "7rem",
    "12rem",
  ],
  fontWeights: {
    body: 400,
    heading: 700,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  colors: {
    text: "#000",
    background: "#fff",
    primary: "#6e1fad",
    secondary: "#3c22be",
    muted: "#f6f6f6",
    accent: "#ccb81e",
    primaryOpaque: "rgba(110,31,173,0.75)",
    secondaryOpaque: "rgba(60,34,190,0.25)",
    accentOpaque: "rgba(204,184,30,0.25)",
  },
  borders: {
    card: "8px solid #141414",
  },
  text: {
    mainHeading: {
      fontSize: ["2.25rem", 4, 5, 6, 7],
      textTransform: "capitalize",
      // transform: "skew(-2deg, 3deg)",
      margin: ["30px", null, "50px"],
      position: "relative",
      letterSpacing: "-3px",
      color: "black",
      display: "inline",
      transform: "skew(-10deg, -5deg)",
      textShadow:
        "-1px -1px 0 #000,	1px -1px 0 #000,-1px 1px 0 #000,1px 1px 0 #000;",

      "&:before": {
        content: "attr(title)",
        position: "absolute",
        left: "-5px",
        top: ["-15px", "-25px", "-40px"],
        color: "primaryOpaque",
        opacity: 0.5,
        zIndex: -1,
      },

      "&:after": {
        content: "attr(title)",
        position: "absolute",
        left: "5px",
        top: ["15px", "25px", "40px"],
        color: "accentOpaque",
        opacity: 0.5,
        zIndex: -1,
      },
    },
    projectCardHeading: {
      writingMode: "vertical-rl",
      fontSize: [3, null, 4, 5],
      alignSelf: "center",
      color: "muted",
      marginX: "auto",
    },
    cardBody: {
      textAlign: "justify",
      mx: [2, 3, 4],
      fontSize: ["1em", null, null, ".7em"],
    },
    cardTitle: {
      fontSize: ["1.5em"],
      margin: 2,
    },
    bodyText: {},
  },
  links: {
    cardLink: {
      fontSize: ["2em", null, null, "1.25em"],
      textDecoration: "none",
      color: "primary",
      transition: "all .5s ease",
      marginY: 2,
      textShadow: "2px 2px 3px #ccb81e",
      "&:hover": {
        transform: "scale(1.3)",
        color: "secondary",
        textDecoration: "underline overline",
      },
    },
    navLink: {
      textTransform: "uppercase",
      padding: [1, 2, 3, null, null],
      fontSize: [null, null, 2, 3, 4],
      color: "primary",
      bg: "rgba(29,26,29,0.5)",
      borderRadius: "10px",
      transition: "all .2s ease-in",
      textShadow: "3px 2px 4px rgba(234,176,243,1)",
      cursor: "pointer",
      textDecoration: "none",
      "&:hover": {
        color: "secondary",
      },
      "&:active": {
        color: "accent",
      },
    },
    mobileNavLink: {
      textTransform: "uppercase",
      padding: 3,
      fontSize: [3, 4],
      color: "primary",
      transition: "all .2s ease-in",
      textShadow: "3px 2px 4px rgba(234,176,243,1)",
      cursor: "pointer",
      textDecoration: "none",
    },
  },
  images: {
    cardImg: {
      width: "90%",
      height: "auto",
    },
    aboutImg: {
      width: ["90%", null, "60%", null, "50%"],
      borderRadius: "50%",
      marginY: ["30px", null, "50px", null, "70px"],
      boxShadow: "10px 10px 48px 0px rgba(0,0,0,0.5)",
      backgroundColor: "accent",
      padding: "30px",
    },
  },
  cards: {
    projectCard: {
      marginBottom: [5],
      width: ["95vw", "90vw", null, "42vw", "37vw"],
      height: ["95vw", "90vw", null, "42vw", "37vw"],
      position: "relative",
      filter: [null, null, "saturate(.25)"],
      transition: "all 1s ease",
      fontSize: [1, 2, null, 3],

      "&:hover": {
        transform: [null, null, "scale(1.05)"],
        filter: [null, null, "saturate(2)"],
      },

      "& .flipContainerStyle": {
        position: "absolute",
        width: "100%",
        height: "100%",
        cursor: "pointer",
        willChange: "transform, opacity, boxShadow",
        transition: "box-shadow 1s ease",
        display: "flex",
        backgroundColor: "black",
        border: "card",
        borderRadius: "10px",
        boxShadow: "15px 15px 15px -8px rgba(0,0,0,0.5)",
        "&:hover": {
          boxShadow: "18px 18px 18px 0px rgba(0,0,0,0.5)",
        },

        "& .cardBack": {
          width: "95%",
          height: "90%",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "space-evenly",
          backgroundColor: "muted",
        },
      },
    },
  },
  layout: {
    container: {
      display: "flex",
      flexDirection: "column",
      width: ["95%", null, "90%", null, "80%"],
      position: "relative",
      minHeight: "100vh",
    },
  },
  variants: {
    mobileNavMenu: {
      position: "fixed",
      top: 0,
      left: 0,
      width: "100vw",
      height: "100vh",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-evenly",
      flexDirection: "column",
      justifyItems: "space-evenly",
      backgroundColor: "black",
      zIndex: "9999",
    },
    navBarStyle: {
      alignItems: "center",
      justifyContent: "space-between",
      position: "fixed",
      top: 0,
      width: "100%",
      minHeight: 90,
      zIndex: 9998,
      boxShadow: " 0px -2px 25px 0px rgba(0,0,0,0.55)",
    },
    cardContainer: {
      marginTop: "75px",
      display: "flex",
      flexWrap: ["nowrap", null, null, "wrap", null],
      justifyContent: [null, null, null, "space-around"],
      alignItems: ["center"],
      flexDirection: ["column", null, null, "row", null],
      width: "100%",
    },
  },
  forms: {
    label: {
      fontSize: [2, null, 3],
      marginBottom: "5px",
    },
    input: {
      marginBottom: "10px",
      bg: "muted",
      color: "text",
      fontSize: [1, null, 2],
    },
    textarea: {
      minHeight: "150px",
      bg: "muted",
      color: "text",
      resize: "none",
      fontSize: [1, null, 2],
    },
  },
  styles: {
    root: {
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "body",
      background:
        "linear-gradient(349deg, rgba(113,37,164,0.5) 0%, rgba(25,4,48,0.5) 68%, rgba(26,19,187,0.5) 100%)",
      backgroundSize: "cover",
      minHeight: "100vh",
      fontSize: "62.5%",
      borderSizing: "border-box",
    },
  },
}
